### ISSUE TITLE
NullPointerException Error

### ISSUE THREAD

**Issue by RenzHoly** [daimajia/AndroidSwipeLayout#146]
Device MEIZU PRO
Android 5.0.1
ROOTED

```
java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.ViewParent.requestDisallowInterceptTouchEvent(boolean)' on a null object reference
       at com.daimajia.swipe.SwipeLayout.onTouchEvent(SwipeLayout.java:942)
       at android.view.View.dispatchTouchEvent(View.java:8408)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2398)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at in.srain.cube.views.ptr.PtrFrameLayout.dispatchTouchEventSupper(PtrFrameLayout.java:252)
       at in.srain.cube.views.ptr.PtrFrameLayout.dispatchTouchEvent(PtrFrameLayout.java:328)
       at com.ruguoapp.jike.view.JikeRefreshLayout.dispatchTouchEvent(JikeRefreshLayout.java:36)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2346)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1701)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2781)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2303)
       at android.view.View.dispatchPointerEvent(View.java:8598)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4158)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4024)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3571)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3624)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3590)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3700)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3598)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3757)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3571)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3624)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3590)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3598)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3571)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5841)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5815)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5786)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5939)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5902)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5962)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:548)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5226)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by daimajia** [comment]
Which version you are using currently? And what action you are doing when crashing?

**Comment by RenzHoly** [comment]
1.1.9
I don`t know what happened when crashing because the error message is sent by fabric.io

**Comment by RenzHoly** [comment]
1.1.9
I don`t know what happened when crashing because the error message is sent by fabric.io

**Comment by jpshelley** [comment]
@daimajia I know what issue this is:

https://github.com/daimajia/AndroidSwipeLayout/blob/master/library/src/main/java/com/daimajia/swipe/SwipeLayout.java#L918

I ran into it as well. I had this happen when I wasn't inflating SwipeLayout from a layout xml file but programmatically in my tests. If you have a LinearLayout that contains the SwipeLayout then its fine, but if the SwipeLayout is the root view then it has no parent. hence the need for a null pointer check here.

**Comment by daimajia** [comment]
@jpshelley  Make sense! We should check if the `SwipeLayout` is the top layout.

**Comment by RenzHoly** [comment]
but this error dose not happens frequently, I have thousands of users, but I only see it once since.

**Comment by daimajia** [comment]
@RenzHoly Please paste your layout xml here for helping us locate the problem.

**Comment by jpshelley** [comment]
@RenzHoly @daimajia Yeah I'm surprised this hasn't been an issue yet with this library. @daimajia I'm about a week out from sending a pull request for my testing library, so if you want to just do a Hotfix feel free.

**Comment by daimajia** [comment]
@jpshelley Ok, I'll do it! Looking forward to you awesome PR. :-D

**Comment by RenzHoly** [comment]
```xml
<com.daimajia.swipe.SwipeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/swipe"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <RelativeLayout
        android:id="@+id/bottom"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:background="@color/share_background">

        <ImageView
            android:src="@drawable/share"
            style="@style/MessageListItemShareIcon" />
    </RelativeLayout>


    <LinearLayout
        android:id="@+id/surface"
        android:orientation="horizontal"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:baselineAligned="false">

        <RelativeLayout
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1">

            <ImageView
                android:id="@+id/state"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                style="@style/ListItemState" />
        </RelativeLayout>


        <LinearLayout
            android:orientation="vertical"
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="4">

            <TextView
                android:id="@+id/content"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textSize="16sp" />

            <TextView
                android:id="@+id/date"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                style="@style/MessageListItemDate" />
        </LinearLayout>


        <RelativeLayout
            android:layout_width="0dp"
            android:layout_height="match_parent"
            android:layout_weight="1">

            <ImageView
                android:id="@+id/icon"
                style="@style/MessageListItemIcon" />
        </RelativeLayout>
    </LinearLayout>
</com.daimajia.swipe.SwipeLayout>
```

**Comment by gpiazzese** [comment]
Hi,
I'm experiencing the same issue while using the versione 1.2.0.

Here is a part of the stacktrace
```
java.lang.NullPointerException
at com.daimajia.swipe.SwipeLayout.onTouchEvent(SwipeLayout.java:901)
at android.view.View.dispatchTouchEvent(View.java:7706)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
```

And this is how the xml layout is made:
```
<?xml version="1.0" encoding="utf-8"?>
<com.daimajia.swipe.SwipeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:swipe="http://schemas.android.com/apk/res-auto"
    android:id="@+id/id_swipe_row"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    swipe:leftEdgeSwipeOffset="0dp"
    swipe:rightEdgeSwipeOffset="0dp">

    <include
        android:id="@+id/id_bottom_wrapper"
        layout="@layout/aggregated_item_deleted"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:paddingBottom="15dp"
        android:paddingLeft="15dp"
        android:paddingRight="15dp"
        android:paddingTop="15dp">

    </LinearLayout>

</com.daimajia.swipe.SwipeLayout>

```
