### ISSUE TITLE
Crashing during inflation on devices running version lower 5.0

### ISSUE THREAD

**Issue by Michal-easycore** [daimajia/AndroidSwipeLayout#196]
Hi,
I am experiencing strange problem that SwipeLayout keeps crashing during inflation on pre Lollipop devices on following code snippet:

    @Override
    public CampaignSwipeAdapter.SwipeViewHolder onCreateViewHolder(ViewGroup parent, int position) {
        View view = inflater.inflate(R.layout.list_item_swipe_campaign, parent, false);
        return new SwipeViewHolder(view);
    }

See the crash log.

    07-28 04:01:04.891    2556-2556/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #44: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:620)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at com.example.mobile.views.adapter.CampaignSwipeAdapter.onCreateViewHolder(CampaignSwipeAdapter.java:55)
            at com.example.mobile.views.adapter.CampaignSwipeAdapter.onCreateViewHolder(CampaignSwipeAdapter.java:19)
            at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5116)

It seems that it is unable to find SwipeLayout class, but I've got libraries properly set up as follows.

    compile 'com.android.support:recyclerview-v7:22.2.1'
    compile 'com.android.support:support-v4:22.2.1'
    compile "com.daimajia.swipelayout:library:1.2.0@aar"

I've got many other dependencies in project including twitter, facebook or design support lib or Glide so I firstly thought that it might clash somehow, but strange is it's working on my Nexus 5, Android 5.1.1

Any thoughts? Thanks!

**Comment by Michal-easycore** [comment]
Actually the problem was somewhere else. Sorry for misleading issue. :)
