### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: com.daimajia.swipe.SwipeLayout$1

### ISSUE THREAD

**Issue by fenjuly** [daimajia/AndroidSwipeLayout#25]
i'm have trouble using AndroidSwipeLayout, the problem are the same as this one https://groups.google.com/forum/#!topic/ruboto/J--QmJPnMos

i don't know is this  the bug in android studio or your library.

thanks !

**Comment by puliyadivinod** [comment]
Hello Guys, 

Same above issue I am finding in eclipse, How to rectify in eclipse?

Help will be appreciated.

Thanks!

**Comment by daimajia** [comment]
@puliyadivinod You need to import Android support library v4 into your project.  
this may help http://developer.android.com/tools/support-library/setup.html

**Comment by puliyadivinod** [comment]
@daimajia I followed the link still seems no luck for me :(

**Comment by puliyadivinod** [comment]
02-01 23:27:56.619: E/dalvikvm(18170): Could not find class 'com.daimajia.swipe.SwipeLayout$1', referenced from method com.daimajia.swipe.SwipeLayout.<init>
02-01 23:27:56.649: E/AndroidRuntime(18170): FATAL EXCEPTION: main
02-01 23:27:56.649: E/AndroidRuntime(18170): Process: com.vinodp.sourashtranetwork, PID: 18170
02-01 23:27:56.649: E/AndroidRuntime(18170): android.view.InflateException: Binary XML file line #2: Error inflating class com.daimajia.swipe.SwipeLayout
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.support.v4.widget.ResourceCursorAdapter.newView(ResourceCursorAdapter.java:106)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.support.v4.widget.CursorAdapter.getView(CursorAdapter.java:252)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.AbsListView.obtainView(AbsListView.java:2308)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.ListView.makeAndAddView(ListView.java:1790)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.ListView.fillDown(ListView.java:691)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.ListView.fillFromTop(ListView.java:752)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.ListView.layoutChildren(ListView.java:1630)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.AbsListView.onLayout(AbsListView.java:2136)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.View.layout(View.java:15092)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.ViewGroup.layout(ViewGroup.java:4645)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.View.layout(View.java:15092)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.ViewGroup.layout(ViewGroup.java:4645)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.View.layout(View.java:15092)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.ViewGroup.layout(ViewGroup.java:4645)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1520)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.View.layout(View.java:15092)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.ViewGroup.layout(ViewGroup.java:4645)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.View.layout(View.java:15092)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.ViewGroup.layout(ViewGroup.java:4645)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.View.layout(View.java:15092)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.ViewGroup.layout(ViewGroup.java:4645)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.View.layout(View.java:15092)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.ViewGroup.layout(ViewGroup.java:4645)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2014)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1771)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1026)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5776)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.os.Handler.handleCallback(Handler.java:733)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.os.Looper.loop(Looper.java:149)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.app.ActivityThread.main(ActivityThread.java:5268)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at dalvik.system.NativeStart.main(Native Method)
02-01 23:27:56.649: E/AndroidRuntime(18170): Caused by: java.lang.reflect.InvocationTargetException
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at java.lang.reflect.Constructor.constructNative(Native Method)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	... 51 more
02-01 23:27:56.649: E/AndroidRuntime(18170): Caused by: java.lang.NoClassDefFoundError: com.daimajia.swipe.SwipeLayout$1
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at com.daimajia.swipe.SwipeLayout.<init>(SwipeLayout.java:174)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	at com.daimajia.swipe.SwipeLayout.<init>(SwipeLayout.java:62)
02-01 23:27:56.649: E/AndroidRuntime(18170): 	... 54 more

**Comment by dhaval-khant** [comment]
@fenjuly not working for
 com.android.support:support-v4:24.+

**Comment by ThinkLock** [comment]
It's work, thanks!!!

**Comment by Molyakos** [comment]
FATAL EXCEPTION: main
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.daimajia.swipedemo/com.daimajia.swipedemo.MyActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class com.daimajia.swipe.SwipeLayout
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
                                                                            at android.app.ActivityThread.access$600(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
                                                                            at android.os.Handler.dispatchMessage(Handler.java)
                                                                            at android.os.Looper.loop(Looper.java)
                                                                            at android.app.ActivityThread.main(ActivityThread.java)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                         Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class com.daimajia.swipe.SwipeLayout
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java)
                                                                            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java)
                                                                            at android.app.Activity.setContentView(Activity.java)
                                                                            at com.daimajia.swipedemo.MyActivity.onCreate(MyActivity.java:23)
                                                                            at android.app.Activity.performCreate(Activity.java)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
                                                                            at android.app.ActivityThread.access$600(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java) 
                                                                            at android.os.Looper.loop(Looper.java) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                                         Caused by: java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java) 
                                                                            at android.app.Activity.setContentView(Activity.java) 
                                                                            at com.daimajia.swipedemo.MyActivity.onCreate(MyActivity.java:23) 
                                                                            at android.app.Activity.performCreate(Activity.java) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
                                                                            at android.app.ActivityThread.access$600(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java) 
                                                                            at android.os.Looper.loop(Looper.java) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                                         Caused by: java.lang.NoClassDefFoundError: com.daimajia.swipe.SwipeLayout$1
                                                                            at com.daimajia.swipe.SwipeLayout.<init>(SwipeLayout.java:221)
                                                                            at com.daimajia.swipe.SwipeLayout.<init>(SwipeLayout.java:82)
                                                                            at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java) 
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java) 
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java) 
                                                                            at android.app.Activity.setContentView(Activity.java) 
                                                                            at com.daimajia.swipedemo.MyActivity.onCreate(MyActivity.java:23) 
                                                                            at android.app.Activity.performCreate(Activity.java) 
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
                                                                            at android.app.ActivityThread.access$600(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java) 
                                                                            at android.os.Looper.loop(Looper.java) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by ZeevM3** [comment]
hi, i'm having the same problem and can't get it to work...
tried with 
    compile 'com.android.support:recyclerview-v7:20.0.0'
    compile 'com.android.support:support-v4:20.+'
    compile "com.daimajia.swipelayout:library:1.2.0@aar"

and with 23 since my compile version is 23...
    compile 'com.android.support:recyclerview-v7:23.0.0'
    compile 'com.android.support:support-v4:23.+'
    compile "com.daimajia.swipelayout:library:1.2.0@aar"

receive the same error on android studio, inflating the xml
