### ISSUE TITLE
notifyItemChange() is not working in support library v-7:23.1.1

### ISSUE THREAD

**Issue by ishwarverma39** [daimajia/AndroidSwipeLayout#362]
**app is crashing when i am calling notifyItemChange(position)**

below error is there

```
java.lang.AbstractMethodError: abstract method "boolean android.support.v7.widget.RecyclerView$ItemAnimator.animateChange(android.support.v7.widget.RecyclerView$ViewHolder, android.support.v7.widget.RecyclerView$ViewHolder, android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo, android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo)"
                                                                               at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:3062)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2924)
                                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                               at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                               at android.view.View.layout(View.java:16630)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                               at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by daimajia** [comment]
It seems that this issue is not caused by the SwipeLayout.
