### ISSUE TITLE
三星手机（GalaxyOn 7）RecyclerView 删除时崩溃问题。

### ISSUE THREAD

**Issue by songyunbiao** [daimajia/AndroidSwipeLayout#372]
Process: com.daimajia.swipedemo, PID: 9543
                                                                      java.lang.AbstractMethodError: abstract method "boolean android.support.v7.widget.RecyclerView$ItemAnimator.animateChange(android.support.v7.widget.RecyclerView$ViewHolder, android.support.v7.widget.RecyclerView$ViewHolder, android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo, android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo)"
                                                                          at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:3510)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3320)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3080)
                                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
                                                                          at android.view.View.layout(View.java:16992)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                          at android.view.View.layout(View.java:16992)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                          at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
                                                                          at android.view.View.layout(View.java:16992)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                          at android.view.View.layout(View.java:16992)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5409)
                                                                          at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2469)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2171)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1301)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7021)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:590)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:145)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6918)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by PravSonawane** [comment]
Hi.. I got the same error on an emulator (Google Pixel XL running API 24).. I simply updated recyclerview-animators library version in build.gradle file of the demo app of this repo.

FROM -->  compile 'jp.wasabeef:recyclerview-animators:1.0.3@aar'
TO ------> compile 'jp.wasabeef:recyclerview-animators:2.2.6'

Hope this helps.
