### ISSUE TITLE
RecyclerView侧滑Delete崩溃

### ISSUE THREAD

**Issue by wpq2014** [daimajia/AndroidSwipeLayout#437]
## 1. 红米4.4.4崩溃日志:
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.daimajia.swipedemo, PID: 11847
java.lang.AbstractMethodError: abstract method not implemented
    at android.support.v7.widget.RecyclerView$ItemAnimator.animateAppearance(RecyclerView.java)
    at android.support.v7.widget.RecyclerView.animateAppearance(RecyclerView.java:3758)
    at android.support.v7.widget.RecyclerView$4.processAppeared(RecyclerView.java:519)
    at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:247)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3607)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3277)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
    at android.view.View.layout(View.java:14845)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14845)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
    at android.view.View.layout(View.java:14845)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14845)
    at android.view.ViewGroup.layout(ViewGroup.java:4631)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2033)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1790)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1046)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5660)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
    at android.view.Choreographer.doFrame(Choreographer.java:544)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5113)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
    at dalvik.system.NativeStart.main(Native Method)

2. Nexus 5X 6.0.0模拟器崩溃日志：
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.daimajia.swipedemo, PID: 1896
java.lang.AbstractMethodError: abstract method "boolean android.support.v7.widget.RecyclerView$ItemAnimator.animateDisappearance(android.support.v7.widget.RecyclerView$ViewHolder, android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo, android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo)"
    at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:3767)
    at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:514)
    at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:244)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3607)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3277)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
    at android.view.View.layout(View.java:16630)
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at android.view.View.layout(View.java:16630)
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
    at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
    at android.view.View.layout(View.java:16630)
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
    at android.view.View.layout(View.java:16630)
    at android.view.ViewGroup.layout(ViewGroup.java:5437)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
    at android.view.Choreographer.doFrame(Choreographer.java:606)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by chihung93** [comment]
I got a same issue

**Comment by Camsson** [comment]
I got this issue , and  i fix it.
`public class RecyclerViewExample {  `

`   @Override`
     protected void onCreate(Bundle savedInstanceState) {
      
        //annotation L56

       //recyclerView.setItemAnimator(new FadeInLeftAnimator());

 ` }`
`}`
