### ISSUE TITLE
demo recycleview delete item will crash

### ISSUE THREAD

**Issue by SuperLiChen** [daimajia/AndroidSwipeLayout#530]
crash Details:

 Process: com.daimajia.swipedemo, PID: 7175
    java.lang.AbstractMethodError: abstract method "boolean android.support.v7.widget.RecyclerView$ItemAnimator.animateAppearance(android.support.v7.widget.RecyclerView$ViewHolder, android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo, android.support.v7.widget.RecyclerView$ItemAnimator$ItemHolderInfo)"
        at android.support.v7.widget.RecyclerView.animateAppearance(RecyclerView.java:3758)
        at android.support.v7.widget.RecyclerView$4.processAppeared(RecyclerView.java:519)
        at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:247)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3607)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3277)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
        at android.view.View.layout(View.java:17677)
        at android.view.ViewGroup.layout(ViewGroup.java:5594)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17677)
        at android.view.ViewGroup.layout(ViewGroup.java:5594)
        at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:510)
        at android.view.View.layout(View.java:17677)
        at android.view.ViewGroup.layout(ViewGroup.java:5594)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:795)
        at android.view.View.layout(View.java:17677)
        at android.view.ViewGroup.layout(ViewGroup.java:5594)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2577)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2291)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1449)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6674)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:177)
        at android.app.ActivityThread.main(ActivityThread.java:6691)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
    
    
    --------- beginning of system

**Comment by LeeDuHan1** [comment]
You can fix by this way.

RecyclerViewExample.java : 58
//        recyclerView.setItemAnimator(new FadeInLeftAnimator());
