### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by jpnapps** [daimajia/AndroidSwipeLayout#566]
Fatal Exception: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.next(ArrayList.java:860)
at com.daimajia.swipe.SwipeLayout.dispatchSwipeEvent(SwipeLayout.java:518)
at com.daimajia.swipe.SwipeLayout.dispatchSwipeEvent(SwipeLayout.java:497)
at com.daimajia.swipe.SwipeLayout$1.onViewPositionChanged(SwipeLayout.java:387)
at androidx.customview.widget.ViewDragHelper.continueSettling(ViewDragHelper.java:750)
at com.daimajia.swipe.SwipeLayout.computeScroll(SwipeLayout.java:635)
at android.view.View.updateDisplayListIfDirty(View.java:22754)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5320)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5292)
at android.view.View.updateDisplayListIfDirty(View.java:22731)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5320)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5292)
at android.view.View.updateDisplayListIfDirty(View.java:22731)

**Comment by Dieselkaka** [comment]
谢谢，已收到

**Comment by HeroGentry** [comment]
想创业，开网店，低投资，高收入，叫你月月赚翻，美滋滋。本店诚招代理商，包教包会。QQ:2020633271旺旺:梦凌love13
