### ISSUE TITLE
ArrayIndexOutOfBoundsException when dragging 2 list items at once

### ISSUE THREAD

**Issue by ghost** [daimajia/AndroidSwipeLayout#6]
Exception stack is

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1004)
            at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:979)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2073)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2326)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1612)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2494)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2274)
            at android.view.View.dispatchPointerEvent(View.java:8025)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4668)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4556)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4207)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4176)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4261)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4184)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4318)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4207)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4176)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4184)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6302)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6240)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6211)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6382)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6355)
            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6401)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
            at android.view.Choreographer.doFrame(Choreographer.java:559)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:176)
            at android.app.ActivityThread.main(ActivityThread.java:5419)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
            at dalvik.system.NativeStart.main(Native Method)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)

**Comment by dezarion** [comment]
I have same issue, but I have no NineOldAndroid library.

@mitsos21 can you describe what a part of this library was related to this crash?

**Comment by mitsos21** [comment]
I don't use this library, anymore. I really cannot remember. I am sorry.

**Comment by Zhuxf1111** [comment]
@dezarion  Have you resolved it? I'm facing the same issue now.
