### ISSUE TITLE
Scroll freezing when scrolling fast

### ISSUE THREAD

**Issue by ashishoc** [daimajia/AndroidSwipeLayout#74]
I am using same adapter given in demo with some extra view.Everything working charm but if there is big amount of list item (eg. 100) and if user scroll listview with acceleration and accidentally he swipe listitem then listview scroll freezing or scrolling lit bit.If user continuously . If user continuously scroll after freezing (scrolling bit) then after 5-10 scrolling everything working fine again.Hope you understand what I am trying to say but if don't then please check link :
https://docs.google.com/file/d/0B-ikVfqhpHPvQlhJeHhiUzVrejA/edit?usp=docslist_api

**Comment by daimajia** [comment]
Hey, guy, why close this issue?

**Comment by ashishoc** [comment]
sorry for misunderstanding there is build problem,I cleaned my project and working charm.But now I am facing another issue : IndexOutOfBoundsException 
I am trying to remove item from list just like:

    pu.appName().remove(pos);
    pu.appPackage().remove(pos);
    pu.appIconDrawable().remove(pos);
    mAdapter.notifyDataSetChanged();

Everything fine but if scrolled down getting IndexOutOfBoundsException please help me I don't understand what is wrong with adapter.here id adapter:


public class ListViewAdapter extends BaseSwipeAdapter {

	private Context mContext;
	private OnClickCallback callback;
	PackageUtil pu;
	

	public ListViewAdapter(Context mContext,PackageUtil pu) {
		this.mContext = mContext;
	   this.pu=pu;
	}

	@Override
	public int getSwipeLayoutResourceId(int position) {
		return R.id.swipe;
	}

	@Override
	public View generateView(int position, ViewGroup parent) {
		View v = LayoutInflater.from(mContext).inflate(
				R.layout.swipe_item_top, null);
		SwipeLayout swipeLayout = (SwipeLayout) v
				.findViewById(getSwipeLayoutResourceId(position));

		swipeLayout.addSwipeListener(new SimpleSwipeListener() {
			@Override
			public void onOpen(SwipeLayout layout) {
				YoYo.with(Techniques.Tada).duration(500).delay(100)
						.playOn(layout.findViewById(R.id.option1));
				YoYo.with(Techniques.Tada).duration(500).delay(100)
				.playOn(layout.findViewById(R.id.option2));
			}
		});

		swipeLayout
				.setOnDoubleClickListener(new SwipeLayout.DoubleClickListener() {
					@Override
					public void onDoubleClick(SwipeLayout layout,
							boolean surface) {
						
					}
				});
		return v;
	}
	@Override
	public void fillValues(final int position, View convertView) {
		TextView appName = (TextView) convertView.findViewById(R.id.textView1);
		TextView packageName = (TextView) convertView
				.findViewById(R.id.textView2);
		ImageView appIcon = (ImageView) convertView
				.findViewById(R.id.imageView1);
		appName.setText(pu.appName().get(position));
		packageName.setText(pu.appPackage().get(position));
		appIcon.setImageDrawable(pu.appIconDrawable().get(position));
		convertView.findViewById(R.id.option1).setOnClickListener(new View.OnClickListener() {
             public void onClick(View v) {
            	 if(callback != null) {
                     callback.pressedView(v,position);
                  }
             }
         });
	}

	@Override
	public int getCount() {
		return pu.size();
	}

	@Override
	public Object getItem(int position) {
		return null;
	}

	@Override
	public long getItemId(int position) {
		return position;
	}
	
	 public void setCallback(OnClickCallback callback){
	        this.callback = callback;
	 }
	 public interface OnClickCallback {
	        public void pressedView(View view,int position);
	 }
	
}

Here is logcat:

01-24 01:57:02.978: E/ListView(22520): onScrollStateChanged
01-24 01:57:02.988: E/ListView(22520): OnTouch
01-24 01:57:03.008: E/ListView(22520): OnTouch
01-24 01:57:03.018: E/ListView(22520): OnTouch
01-24 01:57:03.038: E/ListView(22520): OnTouch
01-24 01:57:03.048: E/ListView(22520): OnTouch
01-24 01:57:03.058: E/ListView(22520): OnTouch
01-24 01:57:03.058: E/ListView(22520): onScrollStateChanged
01-24 01:57:04.208: D/AndroidRuntime(22520): Shutting down VM
01-24 01:57:04.208: W/dalvikvm(22520): threadid=1: thread exiting with uncaught exception (group=0x430f9140)
01-24 01:57:04.218: E/AndroidRuntime(22520): FATAL EXCEPTION: main
01-24 01:57:04.218: E/AndroidRuntime(22520): java.lang.IndexOutOfBoundsException: Invalid index 160, size is 160
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at java.util.ArrayList.get(ArrayList.java:308)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at com.app.adapters.ListViewAdapter.fillValues(ListViewAdapter.java:72)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at com.daimajia.swipe.adapters.BaseSwipeAdapter.getView(BaseSwipeAdapter.java:53)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.widget.AbsListView.obtainView(AbsListView.java:2283)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.widget.ListView.makeAndAddView(ListView.java:1790)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.widget.ListView.fillDown(ListView.java:691)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.widget.ListView.fillGap(ListView.java:655)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5468)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4470)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.view.Choreographer.doFrame(Choreographer.java:543)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.os.Handler.handleCallback(Handler.java:733)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.os.Looper.loop(Looper.java:149)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at android.app.ActivityThread.main(ActivityThread.java:5268)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
01-24 01:57:04.218: E/AndroidRuntime(22520): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by daimajia** [comment]
Hey guy, I pushed a commit tried to make the SwipeLayout more smooth.

**Comment by daimajia** [comment]
I'll reopen this issue for the second problem you came up with.

**Comment by xiaomeixw** [comment]
删除功能并不是所有的情况都会出现，如何控制AndroidSwipeLayout只显示SurfaceView，底部的BottomView不想在某种特定的情况下使用。没有看到有相关的参数进行控制？望告知并fix

**Comment by Ricardo1980** [comment]
One question @ashishoc, why are you using  R.id.swipe and R.layout.swipe_item_top? I thought it should be the same.
