### ISSUE TITLE
DrawerLayout exception when 2 rows simultaneously dragged 

### ISSUE THREAD

**Issue by remithaunay** [daimajia/AndroidSwipeLayout#91]
I am using this library inside an application containing a DrawerLayout .
When I try to swipe 2 rows at a same time, it causes an exception on the drawer :

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1011)
            at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1111)

It appears that it is caused by the call of requestDisallowInterceptTouchEvent(true) on the parent layout

for more details of the issue and a possible workaround, check this link : 
https://code.google.com/p/android/issues/detail?id=60464#c5

Why does your library need to call requestDisallowInterceptTouchEvent ?

**Comment by jianhao1203** [comment]
hi @remithaunay , have u found any solution for this issue?
